// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestDictionary
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WpfEdit uITxtWordEdit = this.UIDictionaryENWindow.UITxtWordEdit;
            #endregion

            // Type 'wer' in 'txtWord' text box
            uITxtWordEdit.Text = this.RecordedMethod1Params.UITxtWordEditText;
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UIDictionaryENWindow UIDictionaryENWindow
        {
            get
            {
                if ((this.mUIDictionaryENWindow == null))
                {
                    this.mUIDictionaryENWindow = new UIDictionaryENWindow();
                }
                return this.mUIDictionaryENWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UIDictionaryENWindow mUIDictionaryENWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'wer' in 'txtWord' text box
        /// </summary>
        public string UITxtWordEditText = "wer";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIDictionaryENWindow : WpfWindow
    {
        
        public UIDictionaryENWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Dictionary - EN";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Dictionary - EN");
            #endregion
        }
        
        #region Properties
        public WpfEdit UITxtWordEdit
        {
            get
            {
                if ((this.mUITxtWordEdit == null))
                {
                    this.mUITxtWordEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITxtWordEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "txtWord";
                    this.mUITxtWordEdit.WindowTitles.Add("Dictionary - EN");
                    #endregion
                }
                return this.mUITxtWordEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUITxtWordEdit;
        #endregion
    }
}
